cursor #dee3e9
cursor_text_color #bdc8d2

foreground            #dee3e9
background            #0f1418
selection_foreground  #00344d
selection_background  #a3cbea
url_color             #87ceff

color0   #0f1418
color1   #ff729e
color2   #7fff8f
color3   #fff672
color4   #69baf2
color5   #104c76
color6   #87ceff
color7   #eff8ff
color8   #99a0a5
color9   #ff9fbd
color10  #a5ffb0
color11  #fff9a5
color12  #99d5ff
color13  #abdcff
color14  #c9e8ff
color15  #f8fcff
